# docker-compose.yml
# 이 파일은 백엔드와 프런트엔드 컨테이너를 함께 관리하는 멀티 컨테이너 설정을 정의합니다.

version: '3.8'

services:
  # 백엔드 서비스
  backend:
    build:
      context: ./backend # backend 폴더 내의 Dockerfile을 사용하여 이미지를 빌드합니다.
    ports:
      - "5000:5000" # 호스트의 5000번 포트를 컨테이너의 5000번 포트로 매핑합니다.
    volumes:
      - ./backend:/app # 호스트의 backend 폴더를 컨테이너의 /app 디렉토리와 동기화합니다.
                      # 이를 통해 코드 변경 시 컨테이너를 다시 빌드할 필요 없이 바로 반영됩니다.

  # 프런트엔드 서비스
  frontend:
    build:
      context: ./frontend # frontend 폴더 내의 Dockerfile을 사용하여 이미지를 빌드합니다.
    ports:
      - "3000:3000" # Vite의 개발 서버 포트를 매핑합니다.
    volumes:
      - ./frontend:/app # 호스트의 frontend 폴더를 컨테이너의 /app 디렉토리와 동기화합니다.
    depends_on:
      - backend # 프런트엔드 컨테이너는 백엔드가 먼저 시작된 후에 실행됩니다.
